export const siteConfig = {
  name: 'Jose Fernando Gonzales',
  title: 'Jose Fernando Gonzales - Technical Solutions Engineer → AI/ML Engineer',
  description: 'I design, build, and ship ML/LLM features and production-ready apps— from business problem to deploy.',
  url: 'https://solvin-it.github.io',
  author: {
    name: 'Jose Fernando Gonzales',
    email: 'josefernando.a.gonzales@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jose-fernando-gonzales',
    github: 'https://github.com/solvin-it',
  },
  hero: {
    headline: 'Technical Solutions Engineer → AI/ML Engineer',
    subhead: 'I design, build, and ship ML/LLM features and production-ready apps— from business problem to deploy.',
    primaryCTA: 'View Projects',
    secondaryCTA: 'Download CV',
    tertiaryCTA: 'Chat with my AI Butler',
  },
  stats: [
    {
      label: 'Business-First AI Solutions',
      value: '3',
      icon: '🚀',
      tooltip: 'AI applications built to solve real business problems with measurable outcomes',
    },
    {
      label: 'Solutions Engineering Foundation',
      value: '9+ yrs',
      icon: '💼',
      tooltip: 'Deep experience understanding business needs and building practical solutions',
    },
    {
      label: 'End-to-End AI Development',
      value: 'Full Stack',
      icon: '🤖',
      tooltip: 'From problem analysis to deployment - RAG systems, ML pipelines, and web applications',
    },
  ],
  featuredProjects: [
    {
      title: 'RAG on Me (Resume Chatbot)',
      description: 'Intelligent resume assistant with RAG, guardrails, and source attribution for recruiters',
      outcome: 'Enables natural language querying of professional experience with accurate, contextual responses',
      stack: ['Python', 'LangChain', 'Vector Databases', 'RAG', 'FastAPI'],
      slug: 'rag-on-me',
      repoUrl: 'https://github.com/solvin-it/rag-on-me',
      liveUrl: null,
    },
    {
      title: 'Quest to Solvin (RPG Chatbot)',
      description: 'AI-powered RPG chatbot with dynamic storytelling and context-aware responses',
      outcome: 'Showcases advanced prompt engineering and conversational AI design for engaging user experiences',
      stack: ['Python', 'OpenAI API', 'Context Management', 'NLP'],
      slug: 'quest-to-solvin',
      repoUrl: 'https://github.com/solvin-it/quest_to_solvin',
      liveUrl: 'https://quest.solvin.co/',
    },
    {
      title: 'Customer Churn Prediction API',
      description: 'Production-ready ML pipeline with RESTful API for business decision making',
      outcome: 'Demonstrates end-to-end ML deployment from business problem to actionable API service',
      stack: ['Python', 'Scikit-learn', 'FastAPI', 'Docker', 'ML Pipeline'],
      slug: 'customer-churn',
      repoUrl: 'https://github.com/solvin-it/customer-churn-api',
      liveUrl: 'https://churn.solvin.co/',
    },
    {
      title: 'Gentleman\'s POS',
      description: 'Modular Python web application for dual-service business operations (carwash & restaurant)',
      outcome: 'Reduced transaction processing time by 60% across 2 businesses with real-world deployment',
      stack: ['Python', 'Flask', 'SQLModel', 'Docker', 'ESC/POS Printers'],
      slug: 'pos-system',
      repoUrl: 'https://github.com/solvin-it/pos-system',
      liveUrl: null,
    },
  ],
  workPillars: [
    {
      title: 'Understand',
      description: 'Define the real problem, success metrics, and constraints',
      icon: '🎯',
    },
    {
      title: 'Build',
      description: 'Develop. Focusing on practical business value',
      icon: '🔨',
    },
    {
      title: 'Ship',
      description: 'Deploy, measure impact, plan next steps',
      icon: '📦',
    },
  ],
  navigation: [
    { label: 'Projects', href: '/projects' },
    { label: 'Experience', href: '/experience' },
    { label: 'Notes', href: '/notes' },
    { label: 'Resume', href: '/resume' },
    { label: 'Contact', href: '/contact' },
  ],
  seo: {
    keywords: ['Generative AI Engineer', 'Machine Learning', 'Full Stack Developer', 'Technical Solutions', 'RAG', 'LLM'],
    ogImage: '/og-image.jpg',
  },
};