export const siteConfig = {
  name: 'Jose Fernando Gonzales',
  title: 'Jose Fernando Gonzales - Technical Solutions Engineer → AI/ML Engineer',
  description: 'I design, build, and ship ML/LLM features and production-ready apps— from business problem to deploy.',
  url: 'https://solvin-it.github.io',
  author: {
    name: 'Jose Fernando Gonzales',
    email: 'hello@josegonzales.dev',
    linkedin: 'https://linkedin.com/in/josegonzales',
    github: 'https://github.com/solvin-it',
  },
  hero: {
    headline: 'Technical Solutions Engineer → AI/ML Engineer',
    subhead: 'I design, build, and ship ML/LLM features and production-ready apps— from business problem to deploy.',
    primaryCTA: 'View Projects',
    secondaryCTA: 'Download CV',
    tertiaryCTA: 'Chat with my CV',
  },
  stats: [
    {
      label: 'Years shipping software',
      value: '9+',
      icon: '🚀',
      tooltip: 'Professional development experience across multiple industries',
    },
    {
      label: 'FinTech & enterprise delivery',
      value: 'Expert',
      icon: '💼',
      tooltip: 'Specialized in financial technology and enterprise solutions',
    },
    {
      label: 'LLM/RAG & classic ML projects',
      value: '15+',
      icon: '🤖',
      tooltip: 'Machine learning and AI projects delivered end-to-end',
    },
    {
      label: 'Winner: hackathon / academic honors',
      value: '3x',
      icon: '🏆',
      tooltip: 'Multiple competition wins and academic achievements',
    },
  ],
  featuredProjects: [
    {
      title: 'Customer Churn (Telco)',
      description: 'ML classification model with feature engineering and business actionability',
      outcome: 'Reduced churn by 23% through predictive modeling and targeted interventions',
      stack: ['Python', 'Scikit-learn', 'Pandas', 'FastAPI', 'Docker'],
      slug: 'customer-churn',
      repoUrl: 'https://github.com/solvin-it/customer-churn',
      liveUrl: null,
    },
    {
      title: 'Quest To Solvin',
      description: 'RPG-style chatbot with prompt design and state management',
      outcome: 'Interactive storytelling bot with 95% user satisfaction and 40s avg session',
      stack: ['Next.js', 'OpenAI API', 'TypeScript', 'Tailwind CSS', 'Vercel'],
      slug: 'quest-to-solvin',
      repoUrl: 'https://github.com/solvin-it/quest-to-solvin',
      liveUrl: 'https://quest-to-solvin.vercel.app',
    },
    {
      title: 'CV-RAG',
      description: 'On-site chatbot answering about my work with retrieval and citations',
      outcome: 'Intelligent resume assistant with guardrails and source attribution',
      stack: ['Python', 'LangChain', 'ChromaDB', 'FastAPI', 'React'],
      slug: 'cv-rag',
      repoUrl: 'https://github.com/solvin-it/cv-rag',
      liveUrl: null,
    },
    {
      title: 'POS (Carwash/Restaurant)',
      description: 'Browser-based POS with auth, orders, and printing',
      outcome: 'Streamlined operations for 3 businesses, reducing transaction time by 60%',
      stack: ['React', 'Node.js', 'PostgreSQL', 'Socket.io', 'Docker'],
      slug: 'pos',
      repoUrl: 'https://github.com/solvin-it/pos-system',
      liveUrl: null,
    },
  ],
  workPillars: [
    {
      title: 'Understand',
      description: 'Scope the business problem, constraints, metrics',
      icon: '🎯',
    },
    {
      title: 'Build',
      description: 'Iterate quickly; tests; CI/CD; instrumentation',
      icon: '🔨',
    },
    {
      title: 'Ship',
      description: 'Deploy, measure impact, plan next steps',
      icon: '📦',
    },
  ],
  navigation: [
    { label: 'Projects', href: '/projects' },
    { label: 'Experience', href: '/experience' },
    { label: 'Notes', href: '/notes' },
    { label: 'Resume', href: '/resume' },
    { label: 'Contact', href: '/contact' },
  ],
  seo: {
    keywords: ['AI Engineer', 'Machine Learning', 'Full Stack Developer', 'Technical Solutions', 'RAG', 'LLM'],
    ogImage: '/og-image.jpg',
    twitterHandle: '@josegonzales',
  },
};