export const siteConfig = {
  name: 'Jose Fernando Gonzales',
  title: 'Jose Fernando Gonzales - AI Developer | Agentic Systems Engineer',
  description: 'I build agentic AI systems and LLM-powered applications — backed by deep FinTech expertise and 10 years of translating business problems into technical solutions.',
  url: 'https://solvin-it.github.io',
  author: {
    name: 'Jose Fernando Gonzales',
    email: 'josefernando.a.gonzales@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jose-fernando-gonzales',
    github: 'https://github.com/solvin-it',
  },
  hero: {
    headline: 'AI Developer | Agentic Systems Engineer',
    subhead: 'I build agentic AI systems and LLM-powered applications — backed by deep FinTech expertise and 10 years of translating business problems into technical solutions.',
    primaryCTA: 'View Projects',
    secondaryCTA: 'Download CV',
    tertiaryCTA: 'Chat with my AI Butler',
  },
  stats: [
    {
      label: 'Enterprise AI in Production',
      value: 'JPMorgan',
      icon: '🏦',
      tooltip: 'Building agentic AI systems at JPMorganChase using LangChain, LangGraph, and Google ADK',
    },
    {
      label: 'FinTech & Systems Foundation',
      value: '10 yrs',
      icon: '💼',
      tooltip: 'Deep experience in payment systems, solution design, and bridging business needs with technical implementations',
    },
    {
      label: 'AI Architecture Focus',
      value: 'Agentic',
      icon: '🤖',
      tooltip: 'Multi-agent orchestration, RAG systems, and LLM-powered workflows — from design to production',
    },
  ],
  featuredProjects: [
    {
      title: 'RAG on Me (Resume Chatbot)',
      description: 'Intelligent resume assistant with RAG, guardrails, and source attribution for recruiters',
      outcome: 'Enables natural language querying of professional experience with accurate, contextual responses',
      stack: ['Python', 'LangChain', 'Vector Databases', 'RAG', 'FastAPI'],
      slug: 'rag-on-me',
      repoUrl: 'https://github.com/solvin-it/rag-on-me',
      liveUrl: null,
    },
    {
      title: 'Quest to Solvin (RPG Chatbot)',
      description: 'AI-powered RPG chatbot with dynamic storytelling and context-aware responses',
      outcome: 'Showcases advanced prompt engineering and conversational AI design for engaging user experiences',
      stack: ['Python', 'OpenAI API', 'Context Management', 'NLP'],
      slug: 'quest-to-solvin',
      repoUrl: 'https://github.com/solvin-it/quest_to_solvin',
      liveUrl: 'https://quest.solvin.co/',
    },
    {
      title: 'Customer Churn Prediction API',
      description: 'Production-ready ML pipeline with RESTful API for business decision making',
      outcome: 'Demonstrates end-to-end ML deployment from business problem to actionable API service',
      stack: ['Python', 'Scikit-learn', 'FastAPI', 'Docker', 'ML Pipeline'],
      slug: 'customer-churn',
      repoUrl: 'https://github.com/solvin-it/customer-churn-api',
      liveUrl: 'https://churn.solvin.co/',
    },
    {
      title: 'Gentleman\'s POS',
      description: 'Modular Python web application for dual-service business operations (carwash & restaurant)',
      outcome: 'Reduced transaction processing time by 60% across 2 businesses with real-world deployment',
      stack: ['Python', 'Flask', 'SQLModel', 'Docker', 'ESC/POS Printers'],
      slug: 'pos-system',
      repoUrl: 'https://github.com/solvin-it/pos-system',
      liveUrl: null,
    },
  ],
  workPillars: [
    {
      title: 'Understand',
      description: 'Define the real problem, success metrics, and constraints',
      icon: '🎯',
    },
    {
      title: 'Build',
      description: 'Develop. Focusing on practical business value',
      icon: '🔨',
    },
    {
      title: 'Ship',
      description: 'Deploy, measure impact, plan next steps',
      icon: '📦',
    },
  ],
  navigation: [
    { label: 'Projects', href: '/projects' },
    { label: 'Experience', href: '/experience' },
    { label: 'Notes', href: '/notes' },
    { label: 'Resume', href: '/resume' },
    { label: 'Contact', href: '/contact' },
  ],
  seo: {
    keywords: ['AI Developer', 'Agentic AI', 'Generative AI Engineer', 'LangGraph', 'Google ADK', 'Agent Workflows', 'Multi-Agent Systems', 'FinTech AI', 'Machine Learning', 'RAG', 'LLM', 'Technical Solutions'],
    ogImage: '/og-image.jpg',
  },
};